services:
    admin.classe:
        class: GameBundle\Admin\ClasseAdmin
        arguments: [~, GameBundle\Entity\Classe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Classe }
        public: true
